name: Orderbook Data Collection

on:
  schedule:
    # Run every 5 hours to ensure overlap
    - cron: '0 */5 * * *'
  workflow_dispatch:  # Allow manual triggers

jobs:
  collect_data:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours max

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install websockets

    - name: Run collector
      run: python collector.py

    - name: Commit and push if there are changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add *.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Add orderbook data [skip ci]" && git push)